title: <Hello-world />
author: RoscaS
email: sol.rosca@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Take notes and use Ptr !

# twitter_username: RoscaS
github_username:  RoscaS

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- about.html
- blog.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
